### ISSUE TITLE
publishToGitHubPages fails if you have greater than 30 branches alphabetically before gh-pages.

### ISSUE THREAD

**Issue by zarthross** [Kevin-Lee/sbt-github-pages#119]
Very similar to https://github.com/Kevin-Lee/sbt-github-pages/issues/113 I get an error that `gh-pages` does not exist... problem is it does.   The github api repo list endpoint  has a default page size of 30 and the code https://github.com/Kevin-Lee/sbt-github-pages/blob/32477dce3a8ab7a965db1dc920bfb8e0dc9ba16d/src/main/scala/githubpages/github/GitHubApi.scala#L330-L339 appears to take exactly 1 page, of the default size.

**Comment by Kevin-Lee** [comment]
@zarthross Thanks Darren for reporting this bug and you also found the cause! That's great! I really appreciate. 🙂 👍  
I'm on it!

**Comment by Kevin-Lee** [comment]
@zarthross OK, I've fixed it. I'll release it shortly.

**Comment by zarthross** [comment]
Awesome, @Kevin-Lee thanks for the quick work!

**Comment by Kevin-Lee** [comment]
@zarthross Not at all. Your bug report was a lot more valuable as you found the cause which saved my time a lot!

It's been released. https://github.com/Kevin-Lee/sbt-github-pages/releases/tag/v0.8.1
It's already available on the [Maven Central](https://repo1.maven.org/maven2/io/kevinlee/sbt-github-pages_2.12_1.0/0.8.1).

**Comment by zarthross** [comment]
Awesome, thanks again!
